stages:
 - deploy
 
pages:
 stage: deploy
 script:
 - if [ -z "$webroot" ]; then echo "Need to set webroot" && exit 1; fi
 - sudo rsync -rv ./ $webroot --exclude '.git' --exclude '.gitlab-ci.yml' --exclude 'wp-config.php' --exclude '.gitignore' --delete
 - sudo chown root:root $webroot -R
 - cd $webroot
 - sudo chmod -R 777 wp-content/themes/bundl/cache
 
 only:
 - master
